# Generated by Django 2.2.8 on 2020-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
